/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java;

import org.junit.Test;
import static org.junit.Assert.*;

public class HelloWorldTest {
    @Test public void testAppHasAGreeting() {
        HelloWorld classUnderTest = new HelloWorld();
        assertNotNull("application should have a greeting", classUnderTest.getGreeting());
    }
}